#!/usr/bin/python

# Copyright (C) 2013 Nguyen Hung Quy a.k.a dreamer2908
#
# Font stripping script generator v1.0 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

import sys, os, codecs

if len(sys.argv) < 3:
	print("FontForge-based font stripping script generator")
	print("  usage: python font_stripping_script_generator.py [output_pe_script] [text_file_1] ([text_file_2]...)")
	sys.exit()

charlst = []
keepthese = "!@#$%^&*_whatever_you_want_to_keep_in_addition_to_characters_in_those_files"

# processing characters in those text files
for x in range(2, len(sys.argv)):
	fname = sys.argv[x]
	if os.path.isfile(fname):
		f = codecs.open(fname, "r", "utf-8")
		for l in f:
			for c in l[:-1]:
				code = ord(c)
				if code > 255 and not code in charlst:
					charlst.append(code)
		f.close()

# processing additional list
for c in keepthese[:-1]:
	code = ord(c)
	if code > 255 and not code in charlst:
		charlst.append(code)

pe_begin = '''#!/usr/bin/fontforge

/* ----------- Generated by font stripping script generator ------------ */

Open($argv[1]);
SelectNone();

/* Select which glyphs you want to keep. Start with these basic ones */
SelectMore(0u00, 0uff);

/* Insert more here */
'''

pe_more = ''

pe_end = '''
/* Delete the rest by inverting the selection and clear */
SelectInvert();
Clear();

/* Generate output file. See http://fontforge.org/scripting-alpha.html#Generate */
Generate($argv[2], "", 4);
'''

# Insert char list to pe script
charlst.sort()
for c in charlst:
	pe_more = pe_more + ("SelectMore(0u%04x)\n" % c)

# Write pe script to output
pe_script = pe_begin + pe_more + pe_end
f = open(sys.argv[1], 'w')
f.write(pe_script)
f.close()